import { NextRequest, NextResponse } from 'next/server'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { resolveDestination } from '@/lib/auth/resolveDestination'

/**
 * GET /[locale]/auth/confirm
 *
 * Handles three flows:
 *
 *   1. Magic link callback (signup activation) — ?token_hash=...&type=magiclink
 *      Generated by /api/signup and /api/auth/resend-magic-link.
 *   2. Password recovery — ?token_hash=...&type=recovery (or legacy ?code=...&type=recovery)
 *      Generated by /api/auth/forgot-password.
 *   3. Legacy magic-link fallback — ?code=... (kept for any old emails in flight)
 *
 * Routing after session establishment:
 *   - type=recovery (any user state)        → /onboarding/set-password
 *   - Otherwise → resolveDestination() decides:
 *       no restaurant row                   → /onboarding/set-password
 *       status = 'live'                     → /dashboard
 *       status = 'pending_review'           → /onboarding/submitted
 *       status = 'suspended'/'cancelled'    → /login?error=account_unavailable
 *       status = 'onboarding' & step >= 1   → that step's path
 *       status = 'onboarding' & step = 0    → /onboarding (service picker)
 *
 * Failure cases redirect to /verify-email?error={expired|used}.
 *
 * Locale handling:
 *   The redirect target's locale prefix is derived from (in priority order):
 *   1. The ?locale= query param if present and valid (set by signup/resend routes).
 *   2. The [locale] segment of the request URL.
 *   This lets a Dutch-link click land on /en/onboarding when the user signed up in EN.
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ locale: string }> }
) {
  const { locale: pathLocale } = await params
  const url = new URL(request.url)
  const origin = url.origin

  const tokenHash = url.searchParams.get('token_hash')
  const code = url.searchParams.get('code')
  const typeRaw = url.searchParams.get('type')
  const type = typeRaw === 'recovery' ? 'recovery' : 'magiclink'
  const queryLocale = url.searchParams.get('locale')

  const effectiveLocale: 'nl' | 'en' =
    queryLocale === 'en' || queryLocale === 'nl'
      ? queryLocale
      : pathLocale === 'en'
      ? 'en'
      : 'nl'
  const localePrefix = effectiveLocale === 'en' ? '/en' : ''

  // No verification material at all → expired
  if (!tokenHash && !code) {
    return NextResponse.redirect(
      `${origin}${localePrefix}/verify-email?error=expired`
    )
  }

  const supabase = await createSupabaseServerClient()

  // Establish a session via whichever method matches the incoming params.
  let userId: string | null = null
  let exchangeErrorMessage = ''

  if (tokenHash) {
    const { data, error } = await supabase.auth.verifyOtp({
      token_hash: tokenHash,
      type,
    })
    if (error || !data?.user) {
      exchangeErrorMessage = (error?.message || '').toLowerCase()
      console.error('verifyOtp failed in /auth/confirm:', error)
    } else {
      userId = data.user.id
    }
  } else if (code) {
    const { data, error } = await supabase.auth.exchangeCodeForSession(code)
    if (error || !data?.user) {
      exchangeErrorMessage = (error?.message || '').toLowerCase()
      console.error('exchangeCodeForSession failed in /auth/confirm:', error)
    } else {
      userId = data.user.id
    }
  }

  if (!userId) {
    const usedAlready =
      exchangeErrorMessage.includes('used') ||
      exchangeErrorMessage.includes('already')
    const errorParam = usedAlready ? 'used' : 'expired'
    return NextResponse.redirect(
      `${origin}${localePrefix}/verify-email?error=${errorParam}`
    )
  }

  // Recovery flow always goes to set-password regardless of restaurant state.
  if (type === 'recovery') {
    return NextResponse.redirect(
      `${origin}${localePrefix}/onboarding/set-password`
    )
  }

  // Magic-link signup flow — look up the restaurant record for this user.
  const { data: restaurant, error: restaurantError } = await supabase
    .from('restaurants')
    .select('status, current_onboarding_step')
    .eq('user_id', userId)
    .maybeSingle()

  if (restaurantError) {
    console.error('Restaurant lookup error in /auth/confirm:', restaurantError)
    return NextResponse.redirect(
      `${origin}${localePrefix}/onboarding/set-password`
    )
  }

  const destination = resolveDestination(restaurant ?? null, effectiveLocale)
  return NextResponse.redirect(`${origin}${destination}`)
}
